title: tg-chan
email: tg-chan@github.io
description: Write an awesome description for your new site here …
twitter_username: jekyll
github_username: jekyllrb
url:
baseurl:


ANON_DEFAULT: Анон
APPROVE_BOARDS: default, discuss, request, fic, pic, book, transport, vel, voice, magnet, hr
BOARD:
  - default:
      title: /b/
      permalink: /b/
      displayname: Анон
      picture: 1
      media: False
  - request:
      title: /r/
      permalink: /r/
      displayname: Анон
      picture: 1
      media: False
  - discuss:
      title: /dev/
      permalink: /d/
      displayname: Сырно
      picture: 1
      media: False
